services:
  php:
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes
    volumes:
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

  web:
    ports:
      - "7000:80"
      - "7002:443"  # SSL para desarrollo si lo necesitas
